networks:
  gitea:
    external: false

volumes:
    gitea-data:
      driver: local

services:
  server:
    image: docker.io/gitea/gitea:latest-rootless
    container_name: gitea
    user: git
    environment:
      - USER_UID=1002
      - USER_GID=1002
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea        
    restart: always
    networks:
      - gitea
    volumes:
      - /srv/gitea/data:/var/lib/gitea
      - /srv/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - /srv/gitea/postgres:/var/lib/postgresql/data
